import { TimeEntry, Project, Task } from "@/types";
import { elapsedMs, formatDurationShort } from "@/lib/duration";

export interface ReportSummaryData {
  label: string;
  totalMs: number;
  billableMs: number;
  nonBillableMs: number;
  projectRows: { name: string; ms: number; pct: number }[];
  taskRows: { name: string; projectName: string; ms: number }[];
  tagRows: { tag: string; ms: number; pct: number }[];
  entryCount: number;
}

export function buildReportSummaryData(
  entries: TimeEntry[],
  projects: Project[],
  tasks: Task[],
  label: string
): ReportSummaryData {
  const projectMap = new Map(projects.map((p) => [p.id, p]));
  const taskMap = new Map(tasks.map((t) => [t.id, t]));

  const totalMs = entries.reduce(
    (sum, e) => sum + elapsedMs(e.startedAt, e.stoppedAt),
    0
  );
  const billableMs = entries
    .filter((e) => e.billable !== false)
    .reduce((sum, e) => sum + elapsedMs(e.startedAt, e.stoppedAt), 0);
  const nonBillableMs = totalMs - billableMs;

  // Project totals
  const projectMs = new Map<string, number>();
  for (const e of entries) {
    const key = e.projectId ?? "__none__";
    projectMs.set(key, (projectMs.get(key) ?? 0) + elapsedMs(e.startedAt, e.stoppedAt));
  }
  const projectRows = Array.from(projectMs.entries())
    .sort((a, b) => b[1] - a[1])
    .map(([id, ms]) => ({
      name: id === "__none__" ? "No project" : (projectMap.get(id)?.name ?? "Unknown"),
      ms,
      pct: totalMs > 0 ? Math.round((ms / totalMs) * 100) : 0,
    }));

  // Task totals
  const taskMs = new Map<string, number>();
  for (const e of entries) {
    if (e.taskId) {
      taskMs.set(e.taskId, (taskMs.get(e.taskId) ?? 0) + elapsedMs(e.startedAt, e.stoppedAt));
    }
  }
  const taskRows = Array.from(taskMs.entries())
    .sort((a, b) => b[1] - a[1])
    .map(([id, ms]) => {
      const task = taskMap.get(id);
      const proj = task?.projectId ? projectMap.get(task.projectId) : undefined;
      return {
        name: task?.name ?? "Unknown task",
        projectName: proj?.name ?? "",
        ms,
      };
    });

  // Tag totals
  const tagMsMap = new Map<string, number>();
  for (const e of entries) {
    for (const tag of e.tags ?? []) {
      tagMsMap.set(tag, (tagMsMap.get(tag) ?? 0) + elapsedMs(e.startedAt, e.stoppedAt));
    }
  }
  const tagRows = Array.from(tagMsMap.entries())
    .sort((a, b) => b[1] - a[1])
    .map(([tag, ms]) => ({
      tag,
      ms,
      pct: totalMs > 0 ? Math.round((ms / totalMs) * 100) : 0,
    }));

  return {
    label,
    totalMs,
    billableMs,
    nonBillableMs,
    projectRows,
    taskRows,
    tagRows,
    entryCount: entries.length,
  };
}

/** Render the summary as a plain-text/Markdown string ready to paste. */
export function formatReportSummary(data: ReportSummaryData): string {
  if (data.totalMs === 0) return `📊 TaskPotato — ${data.label}\n\nNo tracked time in this period.`;

  const lines: string[] = [];

  lines.push(`📊 TaskPotato — ${data.label}`);
  lines.push("");

  // Totals line
  const billablePct =
    data.totalMs > 0 ? Math.round((data.billableMs / data.totalMs) * 100) : 0;
  if (data.nonBillableMs > 0) {
    lines.push(
      `**Total:** ${formatDurationShort(data.totalMs)}  ` +
        `(Billable: ${formatDurationShort(data.billableMs)} ${billablePct}% · ` +
        `Non-billable: ${formatDurationShort(data.nonBillableMs)} ${100 - billablePct}%)`
    );
  } else {
    lines.push(`**Total:** ${formatDurationShort(data.totalMs)} (all billable)`);
  }
  lines.push(`**Entries:** ${data.entryCount}`);
  lines.push("");

  // Projects
  if (data.projectRows.length > 0) {
    lines.push("**By Project:**");
    for (const { name, ms, pct } of data.projectRows) {
      lines.push(`  • ${name}  ${formatDurationShort(ms)}  (${pct}%)`);
    }
    lines.push("");
  }

  // Tasks
  if (data.taskRows.length > 0) {
    lines.push("**By Task:**");
    for (const { name, projectName, ms } of data.taskRows) {
      const proj = projectName ? `  ·  ${projectName}` : "";
      lines.push(`  • ${name}${proj}  ${formatDurationShort(ms)}`);
    }
    lines.push("");
  }

  // Tags
  if (data.tagRows.length > 0) {
    lines.push("**Tags:**");
    for (const { tag, ms, pct } of data.tagRows) {
      lines.push(`  • #${tag}  ${formatDurationShort(ms)}  (${pct}%)`);
    }
    lines.push("");
  }

  lines.push("_Generated by TaskPotato_");

  return lines.join("\n");
}
